package com.sonar.plugins.mulesoft.sensors.metrics;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Properties;
import java.util.Scanner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.sonar.api.batch.fs.FileSystem;
import org.sonar.api.batch.fs.InputFile;
import org.sonar.api.batch.sensor.Sensor;
import org.sonar.api.batch.sensor.SensorContext;
import org.sonar.api.batch.sensor.SensorDescriptor;
import org.sonar.api.batch.sensor.coverage.NewCoverage;

import com.sonar.plugins.mulesoft.config.PropertyLoader;
import com.sonar.plugins.mulesoft.filters.MuleFileFilter;
import com.sonar.plugins.mulesoft.language.MuleLanguage;
import com.sonar.plugins.mulesoft.metrics.model.CoverageData;
import com.sonar.plugins.mulesoft.util.MetricKeys;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ArrayNode;

/**
 * Sensor for importing MUnit coverage data into SonarQube's coverage model.
 *
 * <p>This sensor processes MUnit coverage reports (typically {@code munit-coverage.json})
 * generated by the MUnit Maven plugin and translates them into SonarQube's standard
 * coverage metrics. It supports both line-level and processor-level coverage tracking.</p>
 *
 * <h3>Coverage Report Processing:</h3>
 * <p>The sensor looks for MUnit coverage reports in the standard Maven target directory:
 * <pre>
 * target/site/munit/coverage/munit-coverage.json
 * </pre>
 * </p>
 *
 * <h3>Coverage Data Model:</h3>
 * <p>MUnit provides two types of coverage information:
 * <ul>
 *   <li><strong>Line Coverage:</strong> Traditional line-by-line execution tracking</li>
 *   <li><strong>Processor Coverage:</strong> MuleSoft-specific coverage of message processors</li>
 * </ul>
 * </p>
 *
 * <h3>JSON Report Structure:</h3>
 * <p>Expected MUnit coverage JSON format:
 * <pre>
 * {
 *   "coverage": {
 *     "application": {
 *       "flowName": "my-flow",
 *       "files": [
 *         {
 *           "flowName": "my-flow",
 *           "name": "src/main/mule/my-app.xml",
 *           "lines": [1, 5, 10, 15],
 *           "lineNumber": [true, false, true, false],
 *           "covered": [true, false, true, false],
 *           "processorCount": 10,
 *           "coveredProcessorCount": 8
 *         }
 *       ]
 *     }
 *   }
 * }
 * </pre>
 * </p>
 *
 * <h3>Integration with SonarQube:</h3>
 * <p>Coverage data is imported into SonarQube's standard coverage metrics:
 * <ul>
 *   <li>{@code lines_to_cover} - Total coverable lines</li>
 *   <li>{@code uncovered_lines} - Lines not executed during testing</li>
 *   <li>{@code line_coverage} - Percentage of lines covered</li>
 * </ul>
 * </p>
 *
 * <h3>File Mapping:</h3>
 * <p>The sensor handles path resolution between MUnit report paths and SonarQube
 * file system paths, ensuring accurate coverage attribution to source files.</p>
 *
 * @see CoverageData for the coverage data model
 * @see MuleFileFilter for file filtering logic
 * @see PropertyLoader for configuration property access
 * @since 1.0.0
 */
public class CoverageImportSensor implements Sensor {

	private final Logger logger = LoggerFactory.getLogger(CoverageImportSensor.class);
	private final ObjectMapper objectMapper = new ObjectMapper();

	/** Mule 4 coverage report path (Maven surefire-based layout) */
	private static final String MUNIT_REPORT_MULE_4 = java.io.File.separator + "target" + java.io.File.separator
			+ "site" + java.io.File.separator + "munit" + java.io.File.separator + "coverage" + java.io.File.separator
			+ "munit-coverage.json";

	/** Mule 3 coverage report path (legacy layout) */
	private static final String MUNIT_REPORT_MULE_3 = java.io.File.separator + "target" + java.io.File.separator
			+ "munit-reports" + java.io.File.separator + "coverage-json" + java.io.File.separator + "report.json";

	@Override
	public void describe(SensorDescriptor descriptor) {
		descriptor.name("Compute the coverage of the applications");
		descriptor.onlyOnLanguage(MuleLanguage.LANGUAGE_KEY);
	}

	@Override
	public void execute(SensorContext context) {
		String baseDir = context.fileSystem().baseDir().getAbsolutePath();
		File munitJsonReport = new File(baseDir + MUNIT_REPORT_MULE_4);
		if (!munitJsonReport.exists()) {
			// Fall back to Mule 3 report path
			munitJsonReport = new File(baseDir + MUNIT_REPORT_MULE_3);
			if (munitJsonReport.exists()) {
				logger.info("Using Mule 3 coverage report: {}", munitJsonReport.getPath());
			}
		}
		if (munitJsonReport.exists()) {
			Map<String, CoverageData> coverage = loadResults(
					PropertyLoader.getProperties(), munitJsonReport);
			if (!coverage.isEmpty()) {
				FileSystem fs = context.fileSystem();
				Iterable<InputFile> files = fs.inputFiles(new MuleFileFilter(new MuleLanguage(context.config()).getFileSuffixes()));
				for (InputFile file : files) {
					saveCoverage(coverage, file.filename(), context, file);
				}
			}
		}
	}

	private Map<String, CoverageData> loadResults(Properties props, File munitJsonReport) {
		Map<String, CoverageData> coverageMap = new HashMap<>();
		try (Scanner scanner = new Scanner(munitJsonReport)) {

			String jsonInput = scanner.useDelimiter("\\Z").next();
			JsonNode root = objectMapper.readTree(jsonInput);
			String coverage = root.get(props.getProperty(MetricKeys.MUNIT_COVERAGE)).asString();
			logger.debug("Total Coverage: {}", coverage);
			ArrayNode files = (ArrayNode) root.get(props.getProperty(MetricKeys.MUNIT_FILES));
			coverageMap = new HashMap<String, CoverageData>();
			for (Iterator<JsonNode> iterator = files.iterator(); iterator.hasNext();) {
				JsonNode node = iterator.next();
				String name = node.get(props.getProperty(MetricKeys.MUNIT_NAME)).asString();
				CoverageData counter = new CoverageData();
				ArrayNode flows = (ArrayNode) node.get(props.getProperty(MetricKeys.MUNIT_FLOWS));
				for (Iterator<JsonNode> flowsIterator = flows.iterator(); flowsIterator.hasNext();) {
					JsonNode flowNode = flowsIterator.next();
					int messageProcessorCount = flowNode.get(props.getProperty(MetricKeys.MUNIT_PROCESSOR_COUNT)).asInt();
					int coveredProcessorCount = flowNode.get(props.getProperty(MetricKeys.MUNIT_COVERED_PROCESSOR_COUNT)).asInt();
					counter.addProcessors(messageProcessorCount);
					counter.addCoveredProcessors(coveredProcessorCount);
					ArrayNode lines = (ArrayNode) flowNode.get(props.getProperty(MetricKeys.MUNIT_LINES));
					if (lines != null) {
						counter.setHasLineNumbers(true);
						for (Iterator<JsonNode> linesIterator = lines.iterator(); linesIterator.hasNext();) {
							JsonNode linesNode = linesIterator.next();
							int lineNumber = linesNode.get(props.getProperty(MetricKeys.MUNIT_LINE_NUMBER)).asInt();
							boolean covered = linesNode.get(props.getProperty(MetricKeys.MUNIT_COVERED)).asBoolean();

							if (covered) {
								counter.getCoveredLines().add(lineNumber);
							} else {
								counter.getNotcoveredLines().add(lineNumber);
							}
						}
					}
				}
				String[] fileParts;
				if (name.contains(File.separator))
					fileParts = name.split(File.separator);
				else if (name.contains("/") && "\\".equals(File.separator))
					fileParts = name.split("/");
				else
					fileParts = new String[] { name };
				coverageMap.put(fileParts[fileParts.length - 1], counter);
				logger.debug("name: {} : coverage: {}", node.get("name"), node.get("coverage"));
			}
		} catch (IOException e) {
			logger.error("Failed to load MUnit coverage report: {}", munitJsonReport.getPath(), e);
		}
		return coverageMap;

	}

	private void saveCoverage(Map<String, CoverageData> coverageMap, String fileName, SensorContext context,
			InputFile file) {

		CoverageData coverage = coverageMap.get(fileName);
		if (coverage != null) {
			NewCoverage newCoverage = context.newCoverage().onFile(file);

			if (coverage.hasLineNumbers()) {
				for (Iterator<Integer> iterator = coverage.getCoveredLines().iterator(); iterator.hasNext();) {
					Integer lineNumber = iterator.next();
					newCoverage.lineHits(lineNumber, 1);
				}
				for (Iterator<Integer> iterator = coverage.getNotcoveredLines().iterator(); iterator.hasNext();) {
					Integer lineNumber = iterator.next();
					newCoverage.lineHits(lineNumber, 0);
				}
				newCoverage.save();
			} else {
				int processors = coverage.getProcessors();
				int covered = coverage.getCoveredProcessors();

				for (int i = 0; i < processors; i++) {
					newCoverage.lineHits(i + 1, covered > 0 ? 1 : 0);
					covered--;
				}

				newCoverage.save();
			}
		}
	}

}
