apikit=http://www.mulesoft.org/schema/mule/mule-apikit
api-gateway=http://www.mulesoft.org/schema/mule/api-gateway
ee=http://www.mulesoft.org/schema/mule/ee/core
mule=http://www.mulesoft.org/schema/mule/core
munit=http://www.mulesoft.org/schema/mule/munit
munit-tools=http://www.mulesoft.org/schema/mule/munit-tools
context=http://www.springframework.org/schema/context
secure-properties=http://www.mulesoft.org/schema/mule/secure-properties
http=http://www.mulesoft.org/schema/mule/http
scripting=http://www.mulesoft.org/schema/mule/scripting
tls=http://www.mulesoft.org/schema/mule/tls
doc=http://www.mulesoft.org/schema/mule/documentation
validation=http://www.mulesoft.org/schema/mule/validation
java=http://www.mulesoft.org/schema/mule/java
db=http://www.mulesoft.org/schema/mule/db
domain=http://www.mulesoft.org/schema/mule/ee/domain
email=http://www.mulesoft.org/schema/mule/email
jms=http://www.mulesoft.org/schema/mule/jms
sap=http://www.mulesoft.org/schema/mule/sap
sftp=http://www.mulesoft.org/schema/mule/sftp
ftp=http://www.mulesoft.org/schema/mule/ftp
file=http://www.mulesoft.org/schema/mule/file
vm=http://www.mulesoft.org/schema/mule/vm
salesforce=http://www.mulesoft.org/schema/mule/salesforce
workday=http://www.mulesoft.org/schema/mule/workday
servicenow=http://www.mulesoft.org/schema/mule/servicenow
netsuite=http://www.mulesoft.org/schema/mule/netsuite
oracle-ebs=http://www.mulesoft.org/schema/mule/oracle-ebs
sockets=http://www.mulesoft.org/schema/mule/sockets
compression=http://www.mulesoft.org/schema/mule/compression
oauth=http://www.mulesoft.org/schema/mule/oauth
os=http://www.mulesoft.org/schema/mule/os
wsc=http://www.mulesoft.org/schema/mule/wsc
aggregators=http://www.mulesoft.org/schema/mule/aggregators
batch=http://www.mulesoft.org/schema/mule/batch
json=http://www.mulesoft.org/schema/mule/json
xml-module=http://www.mulesoft.org/schema/mule/xml-module
tracing=http://www.mulesoft.org/schema/mule/tracing
jmx=http://www.mulesoft.org/schema/mule/jmx
spring=http://www.mulesoft.org/schema/mule/spring
cloudhub=http://www.mulesoft.org/schema/mule/cloudhub
kafka=http://www.mulesoft.org/schema/mule/kafka
amqp=http://www.mulesoft.org/schema/mule/amqp
redis=http://www.mulesoft.org/schema/mule/redis
mongodb=http://www.mulesoft.org/schema/mule/mongodb
cassandra-db=http://www.mulesoft.org/schema/mule/cassandra-db
ldap=http://www.mulesoft.org/schema/mule/ldap
objectstore=http://www.mulesoft.org/schema/mule/objectstore
f=https://github.com/mulesoft-catalyst/mule-sonarqube-plugin